# Done to increase the memory available to Gradle.
org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true

# IntelliJ IDEA is not yet fully compatible with configuration cache, see: https://github.com/FabricMC/fabric-loom/issues/1349
org.gradle.configuration-cache=false

# Minecraft
minecraft_version=26.2

# Mod Properties
mod_version=0.1.3
mod_group=com.xeno

# Fabric Properties
# check these on https://fabricmc.net/develop
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

# NeoForge Properties
# check these on https://projects.neoforged.net/neoforged/neoforge
neo_version=26.2.0.64
mdg_version=2.0.144
# check these on https://projects.neoforged.net/neoforged/neoform
neoform_version=26.2-2